import type { Scenario } from "./model.ts";

export const catalog: Scenario[] = [
  { id: "capture-replay", title: "Capture and replay", question: "Can Maxwell capture changes and replay their identities?", action: "Create source data, capture events, then replay from the recorded binlog position.", expected: "Ordered events retain their identities. This does not test target replication.", evidence: ["capture.json", "replay.json", "result.json"] },
  { id: "types-keys-ddl", title: "Schema, keys and value boundaries", question: "Do supported schemas and exact values survive the version downgrade?", action: "Exercise composite and changing keys, boundary values, schema changes and drop/recreate.", expected: "Every intended event is accounted for; modeled schemas and values converge without DLQ entries.", evidence: ["expected-events.json", "audit.json", "ledger.json", "assertions.json"] },
  { id: "target-recovery", title: "Target transaction and journal recovery", question: "Can interrupted target writes recover safely?", action: "Inject failures around DML and DDL, replay events and introduce schema drift.", expected: "Rollback, journal recovery, deduplication and drift barriers pass their direct target assertions.", evidence: ["recovery-assertions.json"] },
  ...["append", "crud", "schema-change"].map(id => ({ id, title: ({ append: "Fresh schema and append", crud: "Updates, deletes and repeated writes", "schema-change": "Schema changes during writes" })[id]!, question: "Does the target reproduce every intended operation?", action: "Provision only the source, execute the seeded workload and wait for a final ordered marker.", expected: "Independent event, schema and row assertions agree; no unexpected quarantine.", evidence: ["run-result.json", "manifest.json", "observations.json", "ledger.json"] })),
  { id: "missing-event", title: "Detect missing intermediate events", question: "Can missing changes hide behind matching final rows?", action: "Deliberately omit an intended temporary insert/delete pair.", expected: "The harness fails specifically with event-manifest, and the host validates that expected failure.", evidence: ["host-result.json", "run-result.json"] },
  { id: "wrong-value", title: "Detect incorrect target values", question: "Does the harness detect wrong data even when event counts match?", action: "Deliberately change a target value after the final marker.", expected: "The harness fails specifically with row-mismatch, and the host validates that expected failure.", evidence: ["host-result.json", "run-result.json"] },
  { id: "crash-outage-repair", title: "Crash, outage and repair", question: "Are changes retained across interruption without being applied twice?", action: "Kill the consumer at commit boundaries, restart services, interrupt publication and repair two target-drift failures.", expected: "All changes eventually apply; exactly the expected quarantines are resolved, with identical duplicate diagnostics allowed.", evidence: ["recovery-state.json", "recovery-ledger.json", "recovery-quarantine.json", "host-result.json"] },
  { id: "emulator-loss", title: "Detect emulator queue loss", question: "Does lost broker state fail visibly?", action: "Restart the emulator after recovery checks finish.", expected: "Missing resources cause a visible stop; old checkpoints are not treated as a safe queue rebuild.", evidence: ["recovery-state.json", "host-result.json"] },
  ...["malformed", "unsupported"].map(id => ({ id, title: id === "malformed" ? "Malformed event" : "Unsupported source DDL", question: "Does invalid input block later changes rather than disappear?", action: id === "malformed" ? "Publish invalid JSON, restart and attempt exact-byte repair." : "Execute source MODIFY COLUMN outside the supported policy, restart and attempt exact-byte repair.", expected: "One expected diagnostic preserves the original envelope. Health and unfixed repair fail; the following captured write stays blocked.", evidence: ["load-state.json", "host-result.json"] })),
  { id: "transactions-load", title: "Transactions, rollback and backlog", question: "Do all committed changes arrive while a backlog drains?", action: "Commit multi-table transactions, roll back other writes, rotate binlogs and continue writing during recovery.", expected: "Ordered accounting, schemas and rows match, rollback changes are absent, and no DLQ entries occur. Rates are local measurements, not production SLAs.", evidence: ["load-state.json", "load-ledger.json", "load-metrics.json", "host-result.json"] },
  { id: "complete-suite", title: "Complete scenario suite", question: "Did every mandatory gate finish successfully?", action: "Run all six gates in separate disposable projects.", expected: "All gates pass. Child runs own their event counts; the suite does not add another copy.", evidence: ["suite-result.json", "suite-members.jsonl"] }
];
