import type { Scenario } from "./model.ts";

export const catalog: Scenario[] = [
  { id: "capture-replay", title: "Capture and replay", question: "Can Maxwell capture changes and replay their identities?", action: "Create source data, capture events, then replay from the recorded binlog position.", expected: "Captured and replayed events retain the same order and identities.", evidence: ["capture.json", "replay.json", "result.json"] },
  { id: "types-keys-ddl", title: "Schema, keys and value boundaries", question: "Do supported schemas and exact values survive the version downgrade?", action: "Exercise composite and changing keys, boundary values, schema changes and drop/recreate.", expected: "Every intended event is accounted for; modeled schemas and values converge without DLQ entries.", evidence: ["expected-events.json", "audit.json", "ledger.json", "assertions.json"] },
  { id: "target-recovery", title: "Target transaction and journal recovery", question: "Can interrupted target writes recover safely?", action: "Inject failures around DML and DDL, replay events and introduce schema drift.", expected: "Rollback, journal recovery, deduplication and drift barriers pass their direct target assertions.", evidence: ["recovery-assertions.json"] },
  ...["append", "crud", "schema-change"].map(id => ({ id, title: ({ append: "Create a table and insert rows", crud: "Update and delete rows", "schema-change": "Add a column while writing rows" })[id]!, question: "Does MySQL 5.7 reproduce every planned change from MySQL 8.4?", action: ({append: "Create a source table, insert the configured number of rows and add an index on value.", crud: "Create a source table, insert rows, update the same row twice, delete a row, and insert then delete a temporary row. Add an index on value.", "schema-change": "Create a source table and insert rows. Halfway through, add a note column, update it on an existing row, then fill it on later inserts. Add an index on value."})[id]!, expected: "Both databases match the expected table definitions and rows. Audit messages and target event records account for every planned change, with zero DLQ deliveries.", evidence: ["run-result.json", "manifest.json", "observations.json", "ledger.json"] })),
  { id: "missing-event", title: "Detect two missing changes", question: "Can missing changes hide behind matching final rows?", action: "Skip a planned temporary insert and delete on MySQL 8.4. The final rows still match, but two expected events are missing.", expected: "The event comparison reports event-manifest. The host script checks that this is the exact error, then marks the verifier test passed.", evidence: ["host-result.json", "run-result.json"] },
  { id: "wrong-value", title: "Detect an incorrect target value", question: "Does the harness detect wrong data even when event counts match?", action: "Wait for the source changes to reach MySQL 5.7, then deliberately change a value directly on the target.", expected: "The row comparison reports row-mismatch. The host script checks that this is the exact error, then marks the verifier test passed.", evidence: ["host-result.json", "run-result.json"] },
  { id: "crash-outage-repair", title: "Stop services and repair target rows", question: "Are changes retained across interruption without being applied twice?", action: "Force the consumer to exit during writes, interrupt database and Maxwell services, and remove then restore a target row in two repair checks.", expected: "The planned changes reach MySQL 5.7 exactly once. Both failed updates are retained and later repaired; repeated diagnostic deliveries describe the same original event.", evidence: ["recovery-state.json", "recovery-ledger.json", "recovery-quarantine.json", "host-result.json"] },
  { id: "emulator-loss", title: "Detect lost Pub/Sub subscriptions", question: "Does the consumer report that its subscription has disappeared?", action: "Restart the Pub/Sub emulator after the repair checks finish. Restarting clears its topics and subscriptions.", expected: "The consumer reports the missing subscription and exits. The next test command creates new containers, messaging resources and test data.", evidence: ["recovery-state.json", "host-result.json"] },
  ...["malformed", "unsupported"].map(id => ({ id, title: id === "malformed" ? "Reject invalid JSON" : "Reject an unsupported column change", question: "Does the failed event remain saved while later changes wait?", action: id === "malformed" ? "Send {not-valid-json directly to Pub/Sub, then insert a source row. Restart the consumer and retry the saved message." : "Widen load_a.value from VARCHAR(80) to VARCHAR(120) on MySQL 8.4, then insert a row in load_b. Restart the consumer and retry the saved schema-change event.", expected: "One failed event and its original message are saved with a DLQ diagnostic. The consumer reports that it is blocked, retries fail for the same reason, and the later row remains absent from MySQL 5.7.", evidence: ["load-state.json", "host-result.json"] })),
  { id: "transactions-load", title: "Catch up while more rows are written", question: "Do saved source changes arrive while the consumer catches up?", action: "Stop the consumer while committing changes to both source tables and undoing another transaction with ROLLBACK. Start a new source binary-log file, restart the consumer and insert more rows.", expected: "Committed changes reach MySQL 5.7; the undone transaction contributes no events. Table definitions and rows match, DLQ deliveries stay at zero, and the harness records processing times.", evidence: ["load-state.json", "load-ledger.json", "load-metrics.json", "host-result.json"] },
  { id: "complete-suite", title: "Complete scenario suite", question: "Did every mandatory gate finish successfully?", action: "Run all six gates in separate disposable projects.", expected: "All gates pass. Event counts are reported for each individual run.", evidence: ["suite-result.json", "suite-members.jsonl"] }
];
