import Foundation
import Testing
@testable import ReplicationCore

@Test func exactJSONPreservesBoundaries() throws {
    let number = "12345678901234567890123456789012345.123456789012345678901234567890"
    let json = try ExactJSON(data: Data("{\"n\":\(number),\"u\":18446744073709551615,\"v\":[null,true,\"🐘\\n'\"]}".utf8))
    #expect(json.object?["n"] == .number(number))
    #expect(try ExactJSON(data: Data(json.json.utf8)) == json)
}
@Test func malformedJSONFails() {
    for json in ["01", "1.", "1e", "[1,]", "{\"a\":1,\"a\":2}", "null garbage", "\"unterminated", "[", "{", "NaN"] {
        #expect(throws: (any Error).self) { try ExactJSON(data: Data(json.utf8)) }
    }
}
@Test func boundedDDL() throws {
    let create = try DDLPolicy.parse("CREATE TABLE poc.items (tenant INT, id BIGINT UNSIGNED, value VARCHAR(100), PRIMARY KEY (tenant,id)) ENGINE=InnoDB", eventType: "table-create", table: "items")
    let schema = try create.after(Schema())
    #expect(schema.primaryKey == ["tenant", "id"])
    #expect(schema.columns[0].nullable == false)
    #expect(schema.columns[1].type == "bigint unsigned")
    #expect(create.sql.contains("`tenant` int NOT NULL"))
    let add = try DDLPolicy.parse("ALTER TABLE items ADD COLUMN note VARCHAR(32) NOT NULL DEFAULT 'it''s fine'", eventType: "table-alter", table: "items")
    #expect(try add.after(schema).columns.last?.defaultValue == "it's fine")
    let index = try DDLPolicy.parse("CREATE INDEX by_value ON poc.items (value)", eventType: "table-alter", table: "items")
    #expect(try index.after(schema).indexes.count == 2)
    #expect(Column.normalizeType("BIGINT(20) UNSIGNED") == "bigint unsigned")
    let drop = try DDLPolicy.parse("DROP TABLE `poc`.`items` /* generated by server */", eventType: "table-drop", table: "items")
    #expect(try drop.after(schema).exists == false)
}
@Test func rejectsUnsupportedDDL() {
    for sql in [
        "CREATE TABLE poc.items (id INT PRIMARY KEY, v JSON DEFAULT (JSON_OBJECT())) ENGINE=InnoDB",
        "CREATE TABLE poc.items (id INT PRIMARY KEY) ENGINE=MyISAM",
        "CREATE TABLE poc.items (id INT PRIMARY KEY) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
        "CREATE TABLE other.items (id INT PRIMARY KEY) ENGINE=InnoDB",
        "CREATE TABLE poc.items (id INT PRIMARY KEY) ENGINE=InnoDB; DROP DATABASE poc",
        "CREATE TABLE poc.items (id INT PRIMARY KEY) ENGINE=InnoDB /* comment */",
        "CREATE TABLE poc.items (id INT PRIMARY KEY, v VARCHAR(-1)) ENGINE=InnoDB",
        "CREATE TABLE poc.items (id INT PRIMARY KEY, v DECIMAL(65,31)) ENGINE=InnoDB",
        "CREATE TABLE poc.items (id INT PRIMARY KEY, v JSON DEFAULT 'null') ENGINE=InnoDB",
        "CREATE TABLE poc.items (id INT) ENGINE=InnoDB"
    ] { #expect(throws: (any Error).self) { try DDLPolicy.parse(sql, eventType: "table-create", table: "items") } }
    for sql in ["ALTER TABLE items ADD COLUMN n INT NOT NULL", "ALTER TABLE items DROP COLUMN id", "ALTER TABLE items ADD COLUMN n INT AFTER id"] {
        #expect(throws: (any Error).self) { try DDLPolicy.parse(sql, eventType: "table-alter", table: "items") }
    }
    #expect(throws: (any Error).self) { try quoteIdentifier("items`;DROP DATABASE poc") }
    #expect(throws: (any Error).self) { try DDLPolicy.parse("DROP TABLE poc.items", eventType: "table-create", table: "items") }
}

@Test func schemaPreconditionsAndNormalization() throws {
    let sql = "CREATE TABLE items (id INT PRIMARY KEY, n DECIMAL(10), t DATETIME(0)) ENGINE=InnoDB"
    let plan = try DDLPolicy.parse(sql, eventType: "table-create", table: "items")
    let after = try plan.after(Schema())
    #expect(after.columns[1].type == "decimal(10,0)")
    #expect(after.columns[2].type == "datetime")
    #expect(throws: (any Error).self) { try plan.after(after) }
    let add = try DDLPolicy.parse("ALTER TABLE items ADD COLUMN id INT", eventType: "table-alter", table: "items")
    #expect(throws: (any Error).self) { try add.after(after) }
    let drop = try DDLPolicy.parse("DROP INDEX absent ON items", eventType: "table-alter", table: "items")
    #expect(throws: (any Error).self) { try drop.after(after) }
}
